<?php
$username = $_SESSION['username'];
$PHP_SELF = $_SERVER['PHP_SELF']; 
$argv = "";//$_SERVER['argv']; 
$argc = "";//$_SERVER['argc']; 
$GATEWAY_INTERFACE = $_SERVER['GATEWAY_INTERFACE']; 
$SERVER_ADDR = $_SERVER['SERVER_ADDR']; 
$SERVER_NAME = $_SERVER['SERVER_NAME']; 
$SERVER_SOFTWARE = $_SERVER['SERVER_SOFTWARE']; 
$SERVER_PROTOCOL = $_SERVER['SERVER_PROTOCOL']; 
$REQUEST_METHOD = $_SERVER['REQUEST_METHOD']; 
$REQUEST_TIME = $_SERVER['REQUEST_TIME']; 
$REQUEST_TIME_FLOAT = $_SERVER['REQUEST_TIME_FLOAT']; 
$QUERY_STRING = $_SERVER['QUERY_STRING']; 
$DOCUMENT_ROOT = $_SERVER['DOCUMENT_ROOT']; 
$HTTP_ACCEPT = $_SERVER['HTTP_ACCEPT']; 
$HTTP_ACCEPT_CHARSET = "";//$_SERVER['HTTP_ACCEPT_CHARSET']; 
$HTTP_ACCEPT_ENCODING = ""; 
$HTTP_ACCEPT_LANGUAGE = $_SERVER['HTTP_ACCEPT_LANGUAGE']; 
$HTTP_CONNECTION = "";//$_SERVER['HTTP_CONNECTION']; 
$HTTP_HOST = $_SERVER['HTTP_HOST']; 
$HTTP_REFERER = "";//$_SERVER['HTTP_REFERER']; 
$HTTP_USER_AGENT = $_SERVER['HTTP_USER_AGENT']; 
$HTTPS = "";//$_SERVER['HTTPS']; 
if (!empty($_SERVER['HTTP_CLIENT_IP'])) {
    $REMOTE_ADDR = $_SERVER['HTTP_CLIENT_IP'];
} elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
    $REMOTE_ADDR = $_SERVER['HTTP_X_FORWARDED_FOR'];
} else {
    $REMOTE_ADDR = $_SERVER['REMOTE_ADDR'];
}
$REMOTE_HOST = "";//$_SERVER['REMOTE_HOST']; 
$REMOTE_PORT = $_SERVER['REMOTE_PORT']; 
$REMOTE_USER = "";//$_SERVER['REMOTE_USER']; 
$REDIRECT_REMOTE_USER = "";//$_SERVER['REDIRECT_REMOTE_USER']; 
$SCRIPT_FILENAME = $_SERVER['SCRIPT_FILENAME']; 
$SERVER_ADMIN = "";//$_SERVER['SERVER_ADMIN']; 
$SERVER_PORT = $_SERVER['SERVER_PORT']; 
$SERVER_SIGNATURE = "";//$_SERVER['SERVER_SIGNATURE']; 
$PATH_TRANSLATED = "";//$_SERVER['PATH_TRANSLATED']; 
$SCRIPT_NAME = $_SERVER['SCRIPT_NAME']; 
$REQUEST_URI = $_SERVER['REQUEST_URI']; 
$PHP_AUTH_DIGEST = "";//$_SERVER['PHP_AUTH_DIGEST']; 
$PHP_AUTH_USER = "";//$_SERVER['PHP_AUTH_USER']; 
$PHP_AUTH_PW = "";//$_SERVER['PHP_AUTH_PW']; 
$AUTH_TYPE = "";//$_SERVER['AUTH_TYPE']; 
$PATH_INFO = "";//$_SERVER['PATH_INFO']; 
$ORIG_PATH_INFO = "";//$_SERVER['ORIG_PATH_INFO'];

$sql = "INSERT INTO logged_on_activity (username, PHP_SELF, argv, argc, GATEWAY_INTERFACE, SERVER_ADDR, SERVER_NAME, SERVER_SOFTWARE, SERVER_PROTOCOL, REQUEST_METHOD, REQUEST_TIME, REQUEST_TIME_FLOAT, QUERY_STRING, DOCUMENT_ROOT, HTTP_ACCEPT, HTTP_ACCEPT_CHARSET, HTTP_ACCEPT_ENCODING, HTTP_ACCEPT_LANGUAGE, HTTP_CONNECTION, HTTP_HOST, HTTP_REFERER, HTTP_USER_AGENT, HTTPS, REMOTE_ADDR, REMOTE_HOST, REMOTE_PORT, REMOTE_USER, REDIRECT_REMOTE_USER, SCRIPT_FILENAME, SERVER_ADMIN, SERVER_PORT, SERVER_SIGNATURE, PATH_TRANSLATED, SCRIPT_NAME, REQUEST_URI, PHP_AUTH_DIGEST, PHP_AUTH_USER, PHP_AUTH_PW, AUTH_TYPE, PATH_INFO, ORIG_PATH_INFO) VALUES (:username, :PHP_SELF, :argv, :argc, :GATEWAY_INTERFACE, :SERVER_ADDR, :SERVER_NAME, :SERVER_SOFTWARE, :SERVER_PROTOCOL, :REQUEST_METHOD, :REQUEST_TIME, :REQUEST_TIME_FLOAT, :QUERY_STRING, :DOCUMENT_ROOT, :HTTP_ACCEPT, :HTTP_ACCEPT_CHARSET, :HTTP_ACCEPT_ENCODING, :HTTP_ACCEPT_LANGUAGE, :HTTP_CONNECTION, :HTTP_HOST, :HTTP_REFERER, :HTTP_USER_AGENT, :HTTPS, :REMOTE_ADDR, :REMOTE_HOST, :REMOTE_PORT, :REMOTE_USER, :REDIRECT_REMOTE_USER, :SCRIPT_FILENAME, :SERVER_ADMIN, :SERVER_PORT, :SERVER_SIGNATURE, :PATH_TRANSLATED, :SCRIPT_NAME, :REQUEST_URI, :PHP_AUTH_DIGEST, :PHP_AUTH_USER, :PHP_AUTH_PW, :AUTH_TYPE, :PATH_INFO, :ORIG_PATH_INFO)";

$insert_log = $dbo->prepare("$sql");
$insert_log -> bindValue(":username",$username,PDO::PARAM_STR);
$insert_log -> bindValue(":PHP_SELF",$PHP_SELF,PDO::PARAM_STR);
$insert_log -> bindValue(":argv",$argv,PDO::PARAM_STR);
$insert_log -> bindValue(":argc",$argc,PDO::PARAM_STR);
$insert_log -> bindValue(":GATEWAY_INTERFACE",$GATEWAY_INTERFACE,PDO::PARAM_STR);
$insert_log -> bindValue(":SERVER_ADDR",$SERVER_ADDR,PDO::PARAM_STR);
$insert_log -> bindValue(":SERVER_NAME",$SERVER_NAME,PDO::PARAM_STR);
$insert_log -> bindValue(":SERVER_SOFTWARE",$SERVER_SOFTWARE,PDO::PARAM_STR);
$insert_log -> bindValue(":SERVER_PROTOCOL",$SERVER_PROTOCOL,PDO::PARAM_STR);
$insert_log -> bindValue(":REQUEST_METHOD",$REQUEST_METHOD,PDO::PARAM_STR);
$insert_log -> bindValue(":REQUEST_TIME",$REQUEST_TIME,PDO::PARAM_STR);
$insert_log -> bindValue(":REQUEST_TIME_FLOAT",$REQUEST_TIME_FLOAT,PDO::PARAM_STR);
$insert_log -> bindValue(":QUERY_STRING",$QUERY_STRING,PDO::PARAM_STR);
$insert_log -> bindValue(":DOCUMENT_ROOT",$DOCUMENT_ROOT,PDO::PARAM_STR);
$insert_log -> bindValue(":HTTP_ACCEPT",$HTTP_ACCEPT,PDO::PARAM_STR);
$insert_log -> bindValue(":HTTP_ACCEPT_CHARSET",$HTTP_ACCEPT_CHARSET,PDO::PARAM_STR);
$insert_log -> bindValue(":HTTP_ACCEPT_ENCODING",$HTTP_ACCEPT_ENCODING,PDO::PARAM_STR);
$insert_log -> bindValue(":HTTP_ACCEPT_LANGUAGE",$HTTP_ACCEPT_LANGUAGE,PDO::PARAM_STR);
$insert_log -> bindValue(":HTTP_CONNECTION",$HTTP_CONNECTION,PDO::PARAM_STR);
$insert_log -> bindValue(":HTTP_HOST",$HTTP_HOST,PDO::PARAM_STR);
$insert_log -> bindValue(":HTTP_REFERER",$HTTP_REFERER,PDO::PARAM_STR);
$insert_log -> bindValue(":HTTP_USER_AGENT",$HTTP_USER_AGENT,PDO::PARAM_STR);
$insert_log -> bindValue(":HTTPS",$HTTPS,PDO::PARAM_STR);
$insert_log -> bindValue(":REMOTE_ADDR",$REMOTE_ADDR,PDO::PARAM_STR);
$insert_log -> bindValue(":REMOTE_HOST",$REMOTE_HOST,PDO::PARAM_STR);
$insert_log -> bindValue(":REMOTE_PORT",$REMOTE_PORT,PDO::PARAM_STR);
$insert_log -> bindValue(":REMOTE_USER",$REMOTE_USER,PDO::PARAM_STR);
$insert_log -> bindValue(":REDIRECT_REMOTE_USER",$REDIRECT_REMOTE_USER,PDO::PARAM_STR);
$insert_log -> bindValue(":SCRIPT_FILENAME",$SCRIPT_FILENAME,PDO::PARAM_STR);
$insert_log -> bindValue(":SERVER_ADMIN",$SERVER_ADMIN,PDO::PARAM_STR);
$insert_log -> bindValue(":SERVER_PORT",$SERVER_PORT,PDO::PARAM_STR);
$insert_log -> bindValue(":SERVER_SIGNATURE",$SERVER_SIGNATURE,PDO::PARAM_STR);
$insert_log -> bindValue(":PATH_TRANSLATED",$PATH_TRANSLATED,PDO::PARAM_STR);
$insert_log -> bindValue(":SCRIPT_NAME",$SCRIPT_NAME,PDO::PARAM_STR);
$insert_log -> bindValue(":REQUEST_URI",$REQUEST_URI,PDO::PARAM_STR);
$insert_log -> bindValue(":PHP_AUTH_DIGEST",$PHP_AUTH_DIGEST,PDO::PARAM_STR);
$insert_log -> bindValue(":PHP_AUTH_USER",$PHP_AUTH_USER,PDO::PARAM_STR);
$insert_log -> bindValue(":PHP_AUTH_PW",$PHP_AUTH_PW,PDO::PARAM_STR);
$insert_log -> bindValue(":AUTH_TYPE",$AUTH_TYPE,PDO::PARAM_STR);
$insert_log -> bindValue(":PATH_INFO",$PATH_INFO,PDO::PARAM_STR);
$insert_log -> bindValue(":ORIG_PATH_INFO",$ORIG_PATH_INFO,PDO::PARAM_STR);
if ($insert_log -> execute()){
	//echo "update session id usccess";
	//header("Location: $get_url");
} else {
	echo "fail update session id";
	//header("Location: $get_url");
} 
?>